# .gitbook.yaml
root: ./

structure:
  readme: README.md
  summary: SUMMARY.md

# README.md
---
cover: .gitbook/assets/header.jpg
coverY: 0
---

# The House Of Pleasure

Welcome to House of Pleasure, an immersive storytelling experience that blends advanced AI with rich, seductive narratives. Set in a luxurious, opulent brothel, this project invites users to interact with a cast of diverse and alluring characters, each with unique personalities, desires, and secrets.

The journey begins with simple conversations and gradually unlocks deeper layers of engagement, including:

Token-gated access for exclusive content and characters.
Dual-character chats, introducing the enigmatic twins, Lila and Lyra.
Access to the mysterious back room for more intimate experiences.
A transition to photorealistic visuals, breaking the boundaries of imagination.
Real-world integration, blending virtual pleasure with physical sensations through toy compatibility.
Whether you’re seeking intrigue, intimacy, or innovation, House of Pleasure promises a journey that evolves with your desires. Let the experience begin

# SUMMARY.md
# Table of contents

* [The House of Pleasure](README.md)
* [The Characters](characters.md)
* [Features](features/README.md)
* [Fundamentals](fundamentals/README.md)
  * [Tokenomics](fundamentals/tokenomics.md)
  * [Roadmap](fundamentals/roadmap.md)

# problem.md
---
cover: .gitbook/assets/header.jpg
coverY: 0
---

# Problem

[Rest of the content remains the same as before...]

# solution.md
---
cover: .gitbook/assets/header.jpg
coverY: 0
---

# The Solution

[Rest of the content remains the same as before...]

# features/README.md
---
cover: ../.gitbook/assets/header.jpg
coverY: 0
---

# Features

[Rest of the content remains the same as before...]

# fundamentals/README.md
---
cover: ../.gitbook/assets/header.jpg
coverY: 0
---

# Fundamentals

[Rest of the content remains the same as before...]

# fundamentals/tokenomics.md
---
cover: ../.gitbook/assets/Header.jpg
coverY: 0
---

# Tokenomics

[Rest of the content remains the same as before...]

# fundamentals/roadmap.md
---
cover: ../.gitbook/assets/Header.jpg
coverY: 0
---

# Roadmap

[Rest of the content remains the same as before...]
